name: PDGHEventos
main: me.mchiappinam.pdgheventos.Mainn
version: 1.0
author: mchiappinam
website: http://pdgh.com.br/
depends: Vault
commands:
   evento:
      description: Info.
      usage: /<command>